### PR TITLE
GP-13219 accept failed donation attempts

### PR DESCRIPTION
**Pull request by viliam-ivanov**
Created donation tests:
- basic (mandatory params: contact, amount)
- campaign relation
- utm params
- financial type member dues
- supported payment instruments (SEPA, Credit Card, PayPal, Sofortüberweisung, EPS)
- failed status & cancellation

In donation process:
- added failed & cancel_reason API params
- refactored payment instrument (replaced hard-coded ids)

### CODE REVIEW

**Review by pfigel — CHANGES_REQUESTED** [review]
This looks great - haven't found any bugs and the test coverage is good.

Could you update the documentation in `docs/donations.md` to add the new fields and how they should be used? Once that's done we can ship this. 🚀 

Not sure if we talked about civi/extension docs yet - we generally use MkDocs, there's some civi-specific documentation (with installation instructions, etc.) [here](https://docs.civicrm.org/dev/en/latest/documentation/).

**Comment by pfigel** [comment]
@viliam-ivanov forgot to mention: I added our CI configuration to your branch, so you'd have to pull this first.

**Comment by viliam-ivanov** [comment]
documented failed + cancel_reason in `docs/donations.md`

**Review by pfigel — APPROVED** [review]
LGTM, thanks @viliam-ivanov.

Test failure happens only on civicrm-core master, probably some recent breakage since it still worked last week. I'll check back in a few days and open a core ticket if they haven't fixed it by then.

**Pull request merged**
